id = "mcp-server-sequential-thinking"
name = "Sequential Thinking MCP Server"
description = "Model Context Protocol Server for Sequential Thinking"
version = "0.0.1"
schema_version = 1
authors = ["Jeffrey Guenther <guenther.jeffrey@gmail.com>"]
repository = "https://github.com/LoamStudios/zed-mcp-server-sequential-thinking"

[context_servers.mcp-server-sequential-thinking]
name = "Sequential Thinking MCP Server"
